### ISSUE TITLE
Will not enabled at startup

### ISSUE THREAD

**Issue by SirNiloc** [magemonkeystudio/codex#31]
[22:20:34] [Server thread/INFO]: [Codex] Loading server plugin Codex v1.0.0-R1
[22:20:34] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:20:34] [Server thread/INFO]: [Codex] Enabling Codex v1.0.0-R1
[22:20:34] [Server thread/ERROR]: Error occurred while enabling Codex v1.0.0-R1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at codex-1.0.0-R1.jar/studio.magemonkey.codex.CodexEngine.setupNMS(CodexEngine.java:217) ~[codex-1.0.0-R1.jar:?]
	at codex-1.0.0-R1.jar/studio.magemonkey.codex.CodexEngine.loadCore(CodexEngine.java:172) ~[codex-1.0.0-R1.jar:?]
	at codex-1.0.0-R1.jar/studio.magemonkey.codex.CodexPlugin.onEnable(CodexPlugin.java:92) ~[codex-1.0.0-R1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-33-64c9ee6]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-33-64c9ee6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-33-64c9ee6]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-33-64c9ee6]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.1.jar:1.21.1-33-64c9ee6]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-33-64c9ee6]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-33-64c9ee6]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Unexpected version: 1.21.1-R0.1-SNAPSHOT
	at codex-1.0.0-R1.jar/studio.magemonkey.codex.core.Version.<clinit>(Version.java:40) ~[codex-1.0.0-R1.jar:?]
	... 13 more
[22:20:34] [Server thread/INFO]: [Codex] Disabling Codex v1.0.0-R1

**Comment by Travja** [comment]
We have not yet updated to 1.21.1. Keep an eye out for a new build that mentions 1.21.1 compatibility

**Comment by SirNiloc** [comment]
Thank you, I must have misread the versions list. Cheers!
