### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by Hitman477** [magemonkeystudio/codex#36]
this appears with players join only (not sure)

```
[21:16:31 INFO]: UUID of player CXMorgan is 99aae450-618d-347b-9903-08d5e818e0bf
[21:16:32 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "from" is null
[21:16:32 WARN]:        at codex-1.0.1-R0.3-20240917.024013-1.jar//studio.magemonkey.codex.util.Reflex.getFieldValue(Reflex.java:122)
[21:16:32 WARN]:        at codex-1.0.1-R0.3-20240917.024013-1.jar//studio.magemonkey.codex.util.reflection.DefaultReflectionUtil.getChannel(DefaultReflectionUtil.java:117)
[21:16:32 WARN]:        at codex-1.0.1-R0.3-20240917.024013-1.jar//studio.magemonkey.codex.nms.NMS.getChannel(NMS.java:52)
[21:16:32 WARN]:        at codex-1.0.1-R0.3-20240917.024013-1.jar//studio.magemonkey.codex.nms.packets.PacketManager.getChannel(PacketManager.java:61)
[21:16:32 WARN]:        at codex-1.0.1-R0.3-20240917.024013-1.jar//studio.magemonkey.codex.nms.packets.PacketManager.injectPlayer(PacketManager.java:85)
[21:16:32 WARN]:        at codex-1.0.1-R0.3-20240917.024013-1.jar//studio.magemonkey.codex.nms.packets.PacketManager.onJoin(PacketManager.java:122)
[21:16:32 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source)
[21:16:32 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[21:16:32 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:16:32 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:16:32 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:16:32 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[21:16:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[21:16:32 WARN]:        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347)
[21:16:32 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173)
[21:16:32 WARN]:        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
[21:16:32 WARN]:        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13)
[21:16:32 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[21:16:32 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:16:32 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[21:16:32 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[21:16:32 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
[21:16:32 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[21:16:32 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[21:16:32 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
[21:16:32 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
[21:16:32 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[21:16:32 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
[21:16:32 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471)
[21:16:32 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316)
[21:16:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[21:16:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:16:32 ERROR]: Could not pass event PlayerJoinEvent to Codex v1.0.1-R0.3-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.pipeline()" because the return value of "studio.magemonkey.codex.nms.packets.PacketManager.getChannel(org.bukkit.entity.Player)" is null
        at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.nms.packets.PacketManager.injectPlayer(PacketManager.java:85) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
        at codex-1.0.1-R0.3-20240917.024013-1.jar/studio.magemonkey.codex.nms.packets.PacketManager.onJoin(PacketManager.java:122) ~[codex-1.0.1-R0.3-20240917.024013-1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-DEV-9982201]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[linearpaper-1.21.1.jar:1.21.1-DEV-9982201]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Server Software: paper 1.21.1
Fabled Version: fabled-1.0.1-R0.6-20240917.023949-1
Codex Version: codex-1.0.1-R0.3-20240917.024013-1
Divinity Version: divinity-1.0.1-R0.3-20240924.052643-1

**Comment by Hitman477** [comment]
I tried on standart paper and its appears
